//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 examSystem.rc 使用
//
#define brithOrprof5                    0
#define stuSaveBtn                      1
#define ReturnLogin                     2
#define exitInputTest                   2
#define SaveEditTestSingle              4
#define uploadSingleTest                8
#define TestSingleDel                   10
#define TestSingleFind                  11
#define ViewOtherTest                   12
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define ADD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXAMSYSTEM_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     137
#define INFOR_add                       140
#define INFOR_ADD                       140
#define IDD_DIALOG2                     142
#define IDD_DIALOG3                     144
#define IDD_DIALOG4                     146
#define IDD_DIALOG5                     148
#define IDD_CStudentDlg                 159
#define TeacherDlg                      160
#define ManagerDlg                      161
#define IDD_Register                    165
#define IDD_InputSingleTest             167
#define IDD_CourseInfo                  169
#define IDD_QueryUser                   171
#define IDD_EditUserInfo                173
#define IDD_EditPwd                     175
#define IDD_OnlineTest                  177
#define IDD_MakePaper                   179
#define IDD_PreviewPaper                181
#define IDD_SysMakePaper                183
#define IDD_EditstuInfo                 184
#define IDD_EditstuInfo1                185
#define IDD_AddstuInfo                  185
#define IDD_ManagerStu                  186
#define IDD_ManagerStuMark              187
#define IDD_allUser                     188
#define IDD_TestManager                 190
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_EDIT1                       1002
#define IDC_BUTTON3                     1002
#define IDC_EDIT2                       1003
#define IDC_BUTTON4                     1003
#define IDC_EDIT3                       1004
#define IDC_BUTTON20                    1004
#define IDC_EDIT4                       1005
#define IDC_BUTTON21                    1005
#define IDC_COMBO1                      1006
#define IDC_EDIT6                       1006
#define IDC_BUTTON22                    1006
#define IDC_EDIT7                       1007
#define IDC_COMBO2                      1007
#define IDC_LIST2                       1008
#define IDC_EDIT8                       1008
#define IDC_COMBO3                      1008
#define IDC_EDIT9                       1009
#define IDC_EDIT11                      1010
#define IDC_BUTTON13                    1010
#define IDC_BUTTON15                    1011
#define IDC_EDIT12                      1011
#define IDC_BUTTON16                    1012
#define IDC_EDIT13                      1012
#define IDC_EDIT14                      1013
#define IDC_EDIT15                      1014
#define IDC_EDIT5                       1015
#define IDC_EDIT16                      1015
#define IDC_BUTTON7                     1016
#define IDC_BUTTON17                    1016
#define IDC_EDIT17                      1016
#define IDC_BUTTON5                     1017
#define IDC_BUTTON18                    1017
#define IDC_EDIT18                      1017
#define IDC_BUTTON8                     1018
#define IDC_BUTTON19                    1018
#define IDC_BUTTON10                    1019
#define IDC_EDIT10                      1020
#define IDC_BUTTON11                    1021
#define IDC_BUTTON12                    1022
#define IDC_BUTTON6                     1025
#define IDC_BUTTON14                    1026
#define IDC_BUTTON9                     1027
#define IDC_MFCLINK1                    1029
#define IDC_MFCLINK2                    1030
#define IDOK                            1031
#define IDCANCEL                        1032
#define IDC_REG                         1033
#define IDOK2                           1033
#define IDC_TREE1                       1034
#define IDOK3                           1034
#define IDC_LIST1                       1035
#define IDCANCEL2                       1035
#define IDC_LIST3                       1036
#define IDC_CHECK2                      1039
#define IDC_CHECK3                      1040
#define IDC_RADIO1                      1040
#define IDC_CHECK4                      1041
#define IDC_RADIO2                      1041
#define IDC_CHECK5                      1042
#define IDC_SCROLLBAR1                  1042
#define IDC_CHECK7                      1044
#define IDC_CHECK1                      1044
#define IDC_CHECK8                      1045
#define IDC_CHECK6                      1045
#define IDC_TAB1                        1045
#define IDC_CHECK9                      1046
#define IDC_CHECK10                     1047
#define IDC_REGBTN                      1047
#define IDC_CHECK11                     1048
#define IDC_StuTest                     1048
#define IDC_CHECK12                     1049
#define IDC_StuResult                   1050
#define IDC_ExitStu                     1051
#define IDC_CurUser                     1052
#define IDC_userDetailBtn               1053
#define IDC_TestList                    1054
#define IDC_TestTree                    1054
#define IDC_InCourse                    1055
#define IDC_teachDetailBtn              1056
#define IDC_managerStu                  1057
#define IDC_InTest                      1058
#define IDC_MakerPaperH                 1059
#define IDC_MakerPaperS                 1060
#define IDC_TeacExit                    1061
#define IDC_courseNameInTest            1062
#define IDC_TestedList                  1063
#define IDC_courseNameI                 1064
#define IDC_testTypeI                   1065
#define IDC_testValueI                  1066
#define IDC_QDiffI                      1067
#define IDC_UpLoadI                     1068
#define IDC_QCententI                   1069
#define IDC_QAnswerI                    1070
#define IDC_QDetailI                    1071
#define NextTest                        1072
#define brithOrprof7_                   1073
#define brithOrprof9_                   1074
#define brithOrprof5_                   1075
#define IDC_ManagerStuLIST2             1076
#define IDC_TestNum                     1077
#define brithOrprof                     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
